### ISSUE TITLE
Private Server Access Codes

### ISSUE THREAD

**Issue by KLNXXX** [h0nde/problox#1]
I was curious whether or not there was a Roblox endpoint for fetching private server "access codes", seeing that it was needed when fetching the join-script URL for a private server.

The only method I know of is going into your computer's client logs and searching for the access code each time you join a private server. However, this is unreliable considering how quickly the codes change.

**Comment by h0nde** [comment]
Go to the link to your private server, open inspect element, and search for `joinPrivateGame`. The arguments of this call will contain the `place_id`, `access_code` and `link_code`.

**Comment by KLNXXX** [comment]
Thanks for the quick response!

Although this method does work, do you know whether or not I can fetch them purely through HTTP requests?

**Comment by h0nde** [comment]
```python
from problox import Problox
import re

rbx = Problox.from_cookiefile("cookies.txt")

def get_private_server_info(url):
    resp = rbx.request("GET", url)
    place_id, access_code, link_code = re.search(
        "Roblox\.GameLauncher\.joinPrivateGame\((\d+),'(.+?)','(.+?)'\)",
        resp.text).groups()
    return int(place_id), access_code, link_code

url = "https://www.roblox.com/games/914010731/NEW-MASK-SHOP-Ro-Ghoul-ALPHA?privateServerLinkCode=05470025659168335542976019262954"
place_id, access_code, link_code = get_private_server_info(url)

client = rbx.join_private_game_server(place_id, access_code, link_code)
client.wait()
```

**Comment by KLNXXX** [comment]
Thank you so much for the help!
